import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import { addDoc, getDocs, query, where } from "firebase/firestore";
import { storage, roomsCollection } from "../firebase/client";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";

export const createRoom = createAsyncThunk(
  "rooms/create",
  async (formData, { rejectWithValue }) => {
    try {
      const roomsRef = ref(storage, "rooms/" + formData.photo.name);

      const { name, capacity, photo } = formData;

      const snapshot = await uploadBytes(roomsRef, photo);
      const photoLink = await getDownloadURL(snapshot.ref);

      return await addDoc(roomsCollection, {
        name,
        capacity,
        photo: photoLink,
      });
    } catch (error) {
      return rejectWithValue(error);
    }
  }
);

export const getRoomList = createAsyncThunk(
  "rooms/getRoomList",
  async ({ rejectWithValue }) => {
    try {
      const roomDocs = await getDocs(roomsCollection);

      console.log(roomDocs.map((doc) => doc.data()));
    } catch (error) {
      return rejectWithValue(error);
    }
  }
);

const roomsSlice = createSlice({
  name: "rooms",
  initialState: {
    rooms: [],
    loading: "idle",
  },
  extraReducers: {
    [createRoom.pending]: (state, action) => {
      state.loading = "pending";
    },
    [createRoom.fulfilled]: (state, action) => {
      state.loading = "succeeded";
    },
    [createRoom.rejected]: (state, action) => {
      state.loading = "failed";
    },

    [getRoomList]
  },
});

export default roomsSlice.reducer;

// // Add a new document in collection "demoUsers"
// const _createTestUser = async (user) => {
//   // setDoc gives you control of documents id, if you want autogenerated id's see addDoc https://firebase.google.com/docs/firestore/manage-data/add-data#web-version-9
//   await setDoc(doc(db, 'demoUsers', String(user.id)), user)
//   console.log('Document written with ID: ', user.id)
// }
